version: '3.8'
services:
    server:
        image: travel-mate-server
        build:
            context: .
            dockerfile: Dockerfile
        environment:
         - RUST_LOG=debug
         - SRV_HOST=0.0.0.0
         - SRV_PORT=80
        ports:
        - 8081:80